---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxdeployment
  template:
    metadata:
      labels:
        app: nginxdeployment
    spec:
      containers:
      - name: nginxcontainer
        image: docker.io/library/nginx:latest
        resources:
          limits:
            memory: ""
            cpu: ""
        ports:
        - containerPort: 80