---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontenddeployment
  template:
    metadata:
      labels:
        app: frontenddeployment
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/library/nginx:latest
        ports:
        - containerPort: 80
