---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontenddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontenddeployment
  template:
    metadata:
      labels:
        app: frontenddeployment
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/library/nginx:latest
        resources:
          limits:
            memory: ""
            cpu: ""
        ports:
        - containerPort: 8080
